
DEFAULT_LANGUAGE: en
AVAILABLE_LANGUAGES: ['en','de']
BIND_PORT: 64554

WORKER_CONCURRENCY: 1
NUM_WORKERS: 1


MODULE_NAME: email_tflite_local
CLASSIFIER_DIR: TFLITE_MODEL
LOG_DIR: logs
LOG_LEVEL: INFO

CLEAR_MODEL_DIR_BEFORE_TRAINING: True


LOGGING: False


MODEL_PATH: ''
VOCAB_PATH: ''

USE_NORMALIZER: True

TOKENIZER_OPTIONS:
  en:
    separators: " ,.?:!$'\"()[]/;@'-"
    retained_separators: ":"
    rules: ["regex", "whitelist", "possessives", "word_interior_characters"]
    options:
      regex:
        patterns: [
          '[a-zA-Z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}',
          '([A-Z]\.){2,}',
          '([a-zA-Z]\.){1,}([a-zA-Z])',
          '<(\w*\.)*\w*>',
        ]
      whitelist:
        token_whitelist: ["will.i.am"]
      word_interior_characters:
        interior_characters: "$"
  de:
    separators: " ,.?:!$'\"()[]-’<>/`~#^*_=+|;"
    rules: ["regex"]
    options:
      regex:
        patterns: [
          '[a-zA-Z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}',
          '([A-Z]\.){2,}',
          '([a-zA-Z]\.){1,}([a-zA-Z])',
          '<(\w*\.)*\w*>',
        ]
  ar:
    separators: "و،؛ ,.?:!$'\"()[]،؟"
    rules: ["regex"]
    options:
      regex:
        patterns: [
          '[a-zA-Z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}',
          '([A-Z]\.){2,}',
          '([a-zA-Z]\.){1,}([a-zA-Z])',
          '<(\w*\.)*\w*>',
        ]
